
### post create
POST localhost:8080/api/posts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "제목",
  "content": "내용"
}

> {%
    client.global.set("postId", response.body.data.id)
    client.global.set("refreshToken", response.body.data.refreshToken)
%}

### post get
GET localhost:8080/api/posts/{{postId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### post update
PATCH localhost:8080/api/posts/{{postId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "제목",
  "content": "업데이트 내용"
}

### post like
POST localhost:8080/api/posts/{{postId}}/like
Authorization: Bearer {{accessToken}}

### post unlike
DELETE localhost:8080/api/posts/{{postId}}/like
Authorization: Bearer {{accessToken}}

### post getPage
GET http://localhost:8080/api/posts?page=1&size=10&type=NORMAL
Authorization: Bearer {{accessToken}}


### post delete
DELETE localhost:8080/api/posts/{{post_id}}
Authorization: Bearer {{access_token}}






