### 회원가입
POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "qwer1234!",
  "intro": "im first",
  "nickname": "first"
}

### 회원가입
POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "qwer1234!",
  "intro": "im second",
  "nickname": "second"
}

### 회원탈퇴
POST localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "qwer1234!"
}

### 프로필 수정
PATCH localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "qwer1234!",
  "newPassword": "qwer1234!@",
  "newNickname": "별명 수정 테스트",
  "newIntro": ""
}

### 프로필 조회
GET localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 내 프로필 조회
GET localhost:8080/api/users/myprofile
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 로그아웃
DELETE localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}